header:
    title: Make your workflows
    text: AUTOMATIC
    button: Tell Me More
    buttonlink: "#services" # "#{section}" or "URL/page link"

services:
    title: "Services"
    text: "Enable your team to accomplish more."
    section: services
    list:
      - title: "Automation"
        desc: "Put your time into the tasks that leverage your good judgement and intuition. Leave the redundant, repetetive tasks to the computer. Perform routine analysis for planning, building, public works utilities, dashboarding, and reporting. Extract, transform, import and export data to and from your business formats."
        icon: fas fa-laptop-code #find more at https://fontawesome.com/icons
      - title: "Integration"
        desc: "Stop adding the same information into more than one system. Integration eliminates the need for duplicate and repetetive data entry and allows systems to *talk* to each other. Many systems are compatible with GIS or allow for integration. However, these systems don't talk to each other *out of the box*. Tying your systems together through GIS integrations opens up possibilities like real-time geographic visualization of 3rd-party system information, live dashboards and much more."
        icon: fas fa-link       
      - title: "Implementation"
        desc: "I combine Geographic Information Systems experience with software development know-how to identify how to get from point A to point B with your Geospatial software plan. This also involves Geodatabase design, data migration and transformation, GIS workflow optimization, ArcGIS Desktop Custom Add-ins, and good old-fashioned troubleshooting."
        icon: fas fa-hard-hat

portfolio:
    title: "Portfolio"
    text: "What have I done?! ;)"
    section: portfolio
    

timeline:
    title: "Approach" 
    text: "Anticipate a great experience."
    section: timeline
    events:
      - title: "BUILD YOUR IDEAS"
        year: "You're the expert."
        desc: "I've found that you know your job well and have some of the best ideas of how it could be done better. Often, that involves better tools.<br>**I provide digital tools, custom crafted around your ideas.** So we start with some good questions and intent listening."
        image: fas fa-lightbulb
        alt: 
        align: left
      - title: "HOUSE RULES APPLY"
        year: "Choose your flavor."
        desc: "There's more than one way to... well, I don't know anyone who skins cats. However, I like to deliver tools that improve your ability to do your work using skills you're most familiar and comfortable with. A **variety of language and platform options** enable you to maintain a feeling of control. As upgrades and changes occur, you'll be able to keep things running with minimal training."
        image: fas fa-thumbs-up
        alt: 
        align: right
      - title: "COLLABORATION"
        year: "Be part of the process."
        desc: "I've seen that, as I start to develop tools, customers start to see what's possible, leading to innovations in the way they work and improvements on the original idea. Idea sharing and continued **brainstorming along the way** has always led to something **better than we originally imagined.**"
        image: fas fa-hands-helping
        alt: image alt text
        #align: #default is left       
      - title: "GEOBILITATION"
        year: "Learn how to fly."
        desc: "Even the best tools need a little training. I'd like to make sure your team knows how to use the tools I deliver and has the documentation they need. When I hand over the keys, you'll be ready for **take off!**"
        image: fas fa-plane-departure
        alt: 
        align: right
    end: "Let me<br>be on your<br>team!"

about:
    title: "Approach"
    text: "our story"
    section: about

clients:
    section: clients
    max-height: 100px
    horizontal-scrolling: "" #"yes/no"
    list:
      # - title: "envato"
      #   url: https://github.com/raviriley/agency-jekyll-theme
      #   logo: assets/img/clients/envato.jpg
      # - title: "designmodo"
      #   url: https://github.com/raviriley/agency-jekyll-theme
      #   logo: assets/img/clients/designmodo.jpg
      # - title: "themeforest"
      #   url: https://github.com/raviriley/agency-jekyll-theme
      #   logo: assets/img/clients/themeforest.jpg
      # - title: "Creative Market"
      #   url: https://github.com/raviriley/agency-jekyll-theme
      #   logo: assets/img/clients/creative-market.jpg
    
team:
    title: "A BIT ABOUT ME"
    text: "I'm a husband and father of three. I love telling dad jokes, recreating with my family and, playing table-top games. I really like diving in and learning new things. "
    subtext: I'm humbled by the people all around me who lift and build others up. I'm most inspired by my greatest <a href="https://jesuschrist.churchofjesuschrist.org/who-is-jesus-christ?lang=eng" target="_blank">mentor and friend</a>.
    section: team
    people:
      - name: ""
        role: "Family"
        image: assets/img/team/Family.jpg
        social:
          # - url: https://twitter.com
          #   icon: fab fa-twitter
          # - url: https://facebook.com
          #   icon: fab fa-facebook-f
          # - url: https://linkedin.com
          #   icon: fab fa-linkedin-in
      - name: "Doug Green"
        role: "Geospatial Software Consultant"
        image: assets/img/team/Doug.jpg
        social:
          - url: https://community.esri.com/t5/user/viewprofilepage/user-id/70326
            icon: fas fa-globe-americas
            alt: ESRI GeoNet
          - url: https://www.linkedin.com/in/geobilitydoug/
            icon: fab fa-linkedin-in
            alt: LinkedIn
          - url: https://stackoverflow.com/users/2250424/greengeo
            icon: fab fa-stack-overflow
            alt: Stack Overflow
      - name: ""
        role: "Fun"
        image: assets/img/team/Fun.jpg
        social:
          # - url: https://twitter.com
          #   icon: fab fa-twitter
          # - url: https://facebook.com
          #   icon: fab fa-facebook-f
          # - url: https://linkedin.com
          #   icon: fab fa-linkedin-in
          
contact:
    title: "Tell me about your next project"
    text: "208.685.9355 - doug@geobilityco.com"
    section: contact
    
footer:
    # legal: "Privacy Policy"
    social:
      - url: https://community.esri.com/t5/user/viewprofilepage/user-id/70326
        icon: fas fa-globe-americas
      - url: https://www.linkedin.com/in/geobilitydoug/
        icon: fab fa-linkedin-in
      - url: mailto:doug@geobilityco.com
        icon: fas fa-at


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
